In [1]:
import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

In [2]:
# Read the CSV file into a DataFrame
file_path = '../Data/Raw/survey_data.csv'
df = pd.read_csv(file_path, header=0, dtype=object)

In [3]:
df.iloc[2:,:]

,StartDate,EndDate,Status,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,DistributionChannel,UserLanguage,...,__js_Progress,__js_CaptchaSeen,__js_OpeningStatementSeen,__js_CommitmentRequestSeen,__js_DemographicsSeen,__js_ExampleQuestionSeen,__js_PastVideoQIDs,PROLIFIC_PID,STUDY_ID,SESSION_ID
2,5/1/24 21:30,5/1/24 21:46,IP Address,100,950,TRUE,5/1/24 21:46,R_2mFyXuMw0xGhq49,anonymous,EN,...,15,1,1,1,1,1,NaN,5c791e24266f210012af518d,66323697033362689828dfdf,6632984eea600cf193cc86f7
3,5/1/24 21:32,5/1/24 21:51,IP Address,100,1132,TRUE,5/1/24 21:51,R_5Mg1k6wP14yRnih,anonymous,EN,...,15,1,1,1,1,1,NaN,5a631a73b9e3b50001a6ebd8,66323697033362689828dfdf,663298b162f251a71d7c09ab
4,5/1/24 21:26,5/1/24 21:54,IP Address,100,1645,TRUE,5/1/24 21:54,R_5B8lXO4YHfKHfUJ,anonymous,EN,...,15,1,1,1,1,1,NaN,5eebc1fd5feed239a73d693d,66323697033362689828dfdf,66329754c89ade67073a406b
5,5/1/24 21:31,5/1/24 21:55,IP Address,100,1423,TRUE,5/1/24 21:55,R_2ErW8XvC6N2tDZA,anonymous,EN,...,15,1,1,1,1,1,NaN,6089aa8120d7418a70f3eba7,66323697033362689828dfdf,6632987acacfc3f0baf7bf0f
6,5/1/24 21:24,5/1/24 21:59,IP Address,100,2091,TRUE,5/1/24 21:59,R_3P5E5KoGwh5SatC,anonymous,EN,...,15,1,1,1,1,1,NaN,63fc7ac4c0ba10b71a25a63d,66323697033362689828dfdf,663296d669a5872195662459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,5/10/24 15:23,5/10/24 15:46,IP Address,100,1359,TRUE,5/10/24 15:46,R_5dmSacDanFPOOa5,anonymous,EN,...,15,1,1,1,1,1,"306,722,551,618,315,000,000,000,000,000,000,00...",5fe1053fad8fbab3583b4ecf,663a6eb03adf2ec50b7b89f2,663e1fd0eacfdc715c839f5b
323,5/11/24 14:04,5/11/24 14:29,IP Address,100,1459,TRUE,5/11/24 14:29,R_41iYm9SyiCFRoPv,anonymous,EN,...,15,1,1,1,1,1,"31,233,263,128,256,800,000,000,000,000,000,000...",577bfa3c9fecfe0001a5bcbf,663a6eb03adf2ec50b7b89f2,663f5ec72814424115da5964
324,5/11/24 14:04,5/11/24 14:30,IP Address,100,1547,TRUE,5/11/24 14:30,R_7P1bLiBuznSTRyY,anonymous,EN,...,15,1,1,1,1,1,"251,412,822,843,274,000,000,000,000,000,000,00...",5e332dec41d1cd30b905bdfe,663a6eb03adf2ec50b7b89f2,663f5ec02e128dbb738c9864
325,5/11/24 14:05,5/11/24 14:31,IP Address,100,1577,TRUE,5/11/24 14:31,R_1fcOe9zF7A8itEh,anonymous,EN,...,15,1,1,1,1,1,"31,442,829,359,988,300,000,000,000,000,000,000...",62c1f284b5ce5f4d8840ea7c,663a6eb03adf2ec50b7b89f2,663f5eef7d50f1ec92e1423d
326,5/11/24 14:44,5/11/24 15:19,IP Address,100,2082,TRUE,5/11/24 15:19,R_6LSBpVGR3fVLNgr,anonymous,EN,...,15,1,1,1,1,1,"24,025,823,186,193,300,000,000,000,000,000,000...",62a447d91e71bfacd2e8c006,663a6eb03adf2ec50b7b89f2,663f68247b165c38262a5a57

In [4]:
# Define the list of rating column
intensity_columns = ['joy', 'sadness', 'fear', 'anger', 'disgust', 'surprise', 'other']
sam_columns = ['pleasure', 'arousal', 'dominance']
rating_columns = intensity_columns + ['other_text'] + sam_columns + ['appraisal']

In [5]:
# Define the number of videos and columns per video
num_videos = 10
cols_per_video = 16

In [6]:
# Define a function to extract the video identifier from the column index
def extract_video_id(col_index):
    return (col_index - 45) // cols_per_video + 1

In [7]:
# Initialize a list to store processed rows
processed_rows = []

In [8]:
# Iterate through the rows to process each participant's data
rows = df.iloc[2:,:].iterrows()

for _, row in rows:
    # Set to store the video IDs for the current participant
    videos_to_keep = set()
    # Iterate through columns to identify videos with non-null values
    for col_index in range(45, 8237, cols_per_video):
        non_none_indices = row.iloc[col_index:col_index + cols_per_video].dropna().index
        if len(non_none_indices) > 0:
            video_id = extract_video_id(col_index)
            videos_to_keep.add(video_id)

    # Sort the videos to keep
    videos_to_keep = sorted(videos_to_keep)

    if len(videos_to_keep) != num_videos:
        raise Exception(f"Participant {row.QID3948} rated {len(videos_to_keep)} videos.") 
    
    # List to store the column index range for each video
    column_ranges = []
    for video_id in videos_to_keep:
        start_col = 45 + (video_id - 1) * cols_per_video
        end_col = start_col + cols_per_video
        column_ranges.append(range(start_col + 4, end_col))
    
    for column_range, video_id in zip(column_ranges, videos_to_keep):
        # Construct the processed row with the current participant_id
        processed_row = {'participant_id': row.QID3948}
        processed_row['start_time'] = row.StartDate
        processed_row['end_time'] = row.RecordedDate
        # Extract rating data from the assigned videos
        ratings_vals = row.iloc[column_range]
        # Store the video_id
        processed_row[f'video_id'] = video_id
        # Update the rating values for each column
        processed_row.update({col: val for col, val in zip(rating_columns, ratings_vals)})
        # Append the processed row to the list
        processed_rows.append(processed_row)

In [9]:
# Create a new DataFrame from the processed data
processed_df = pd.DataFrame(processed_rows)

In [10]:
# Exclude participant 5f09fab615ee6b0ab5235b15 and 6632140e3df7840cd7a81131
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "5f09fab615ee6b0ab5235b15"].index)
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "65c349313a148edd8311e6a6"].index)
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "64033cb754a87f6c919f305a"].index)
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "6278270bfb2439bf3abf192d"].index)
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "6347c42aae670afaf618bb62"].index)
# processed_df = processed_df.drop(processed_df[processed_df.participant_id == "59b044b4d98aab00019bad5a"].index) # not sure about this one
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "62bd685ac3edc9ad0d77812b"].index)
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "6151797ab0b64a8275ab4f1e"].index)
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "58954e2dc88c680001dd4b7e"].index)
processed_df = processed_df.drop(processed_df[processed_df.participant_id == "647ffbcfcf8adc8070bc2291"].index)
processed_df = processed_df.reset_index(drop=True)

In [11]:
# Save the processed data to a new CSV file
processed_df.to_csv('../Data/Processed/rating.csv', index=False)

In [12]:
processed_df

,participant_id,start_time,end_time,video_id,joy,sadness,fear,anger,disgust,surprise,other,other_text,pleasure,arousal,dominance,appraisal
0,5c791e24266f210012af518d,5/1/24 21:30,5/1/24 21:46,1,NaN,Very Low,Very Low,NaN,NaN,Low,NaN,NaN,4,3,3,i honestly dont know about this one
1,5c791e24266f210012af518d,5/1/24 21:30,5/1/24 21:46,6,NaN,High,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2,it seemed like something had made the robot sa...
2,5c791e24266f210012af518d,5/1/24 21:30,5/1/24 21:46,59,NaN,Very High,Very Low,NaN,NaN,NaN,NaN,NaN,1,1,1,it seems to be sad and maybe a little confused...
3,5c791e24266f210012af518d,5/1/24 21:30,5/1/24 21:46,61,NaN,Very Low,NaN,Very Low,Very Low,NaN,NaN,NaN,4,3,3,it seemed to be kinda all over the place
4,5c791e24266f210012af518d,5/1/24 21:30,5/1/24 21:46,219,NaN,NaN,High,NaN,NaN,Very Low,NaN,NaN,2,7,4,"it seems like something made the robot scared,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3155,62a447d91e71bfacd2e8c006,5/11/24 14:44,5/11/24 15:19,298,NaN,Very High,NaN,NaN,NaN,NaN,NaN,NaN,1,6,2,"Robot was very sad, and just bumbling about, w..."
3156,62a447d91e71bfacd2e8c006,5/11/24 14:44,5/11/24 15:19,409,NaN,High,NaN,NaN,NaN,NaN,NaN,NaN,1,9,5,It was sad and was singing a sad song - it was...
3157,62a447d91e71bfacd2e8c006,5/11/24 14:44,5/11/24 15:19,438,High,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,7,6,"Robot seemed quite happy, and was going about ..."
3158,62a447d91e71bfacd2e8c006,5/11/24 14:44,5/11/24 15:19,499,NaN,NaN,High,NaN,NaN,Average,NaN,NaN,3,9,5,"Robot was agitated, probably fearful."
3159,62a447d91e71bfacd2e8c006,5/11/24 14:44,5/11/24 15:19,509,NaN,Very High,NaN,NaN,NaN,NaN,NaN,NaN,1,6,3,Robot seemed sad and worried. I think somethi...

In [13]:
processed_df.participant_id.unique()

array(['5c791e24266f210012af518d', '5a631a73b9e3b50001a6ebd8',
       '5eebc1fd5feed239a73d693d', '6089aa8120d7418a70f3eba7',
       '63fc7ac4c0ba10b71a25a63d', '5e58436ebdccf5057ddd9190',
       '656cbb93ba4ac7120453d910', '5b09da13641b1200010eab05',
       '648ddf3aeff70c1f26ff2652', '60089c477baa6b3fba6dbe80',
       '55898937fdf99b7ae47f5c7f', '5e0e72587855d35d4dd68c7d',
       '6165e0b51a883e9db8cc7146', '5e7a4371b86374017acf58c3',
       '59e71a3b1ac65d0001eb47ac', '5e53d2941b233d02960a0dde',
       '5c12521fbf739a0001cfeb03', '589c431f0da7f10001de7407',
       '5f0cfeef098f1e53ff201909', '59b536d60516f6000197c3f9',
       '64543fa5dfed1d0ba8024957', '5a1683aeab721b0001ef8e4c',
       '5f2ac70ca7fb433824928131', '60cdad61f2fc16483e5db0a7',
       '5fbb4b0d5fdea9c55f813ace', '646baaaa73f3e86f2af26ac8',
       '60827ccde4706170115a3bf5', '5d57d77df9a0cd00177fc3da',
       '60a80fbd13aba726d46b8f2e', '63c53d59463365d1a0a23b1e',
       '5b5f15f2fc072a00017da73d', '5d96a61b5d0f1c00117201bd',
       '60fddf7d37552b32ac488583', '6554ff77615f63ff7ded6ac3',
       '657a52d55c7577dc0efc0ce6', '60fff225fb2da6129caf029a',
       '659866bb0eef780a15bfd5b2', '64496637163c530b40210999',
       '58aca85e0da7f10001de92d4', '5e87b28549538b0fdf96b318',
       '65a95289729993e188ae78d1', '645920abcee1cd09e70057cd',
       '63d16b409fc89f6d3a97f281', '65ae8444c7df9852ffacda7d',
       '60aa16c68f8b93c186c5465b', '601bdf107baab35ea427ec7e',
       '653fcb1b0f5d689c00a97629', '5dcccec0092079953154f997',
       '5b0710e7a84dcf0001beee8a', '5ea1dc176205ad0c7c941ca1',
       '5b421b9ac2e3810001763252', '596cad007f8c1e00017cb1ca',
       '5d99fea08b712c0016f416e0', '613e1fe8294a9b1170446af3',
       '5e5afa0fab6bfd2f2bb4b250', '63d14e00e845bfe43cf87708',
       '5fb45df6ce203a13f34ac0af', '63407ac64e6e54d2bbfb6a5a',
       '65be693353421206e0db1565', '5ea597859b1fb6594ac2b470',
       '65b11897c8192342e57e9787', '5fdb2a32414cb63975e0d9c7',
       '5c61cbf25434430001870681', '6428caa789609d52890a3c99',
       '5962f252b692380001417ab9', '642b4dcc167bfad1e097543d',
       '60fd9b084a91f75f655da04f', '5ea6df209d688606829ac644',
       '5d945d41e5ce0a001347e2b5', '64971e71ba666687996c6072',
       '596f003434773e0001fc0d28', '6160717242827a64a55d99ad',
       '578e9a9bfa4465000113f154', '650f26eae8a7cf504ba29660',
       '64e6892cc9dc5cd2ca94bb0a', '640105daa923d3f5f2669039',
       '609140cea1442672dd2141d7', '5f5b4aa99a3ef626581a1473',
       '5e6473fbc15dbe1f71eea95b', '5da74e9437d4210016492810',
       '5e29fd5f2bec3b065e9a729e', '5aea88ec1aff900001cc0e55',
       '65be49c47056d13e2b2fa4b6', '5c4d8d706b23ab0001a34af2',
       '65a04bff3f91fc3cf7f3991b', '5bb0df0871e1b2000176bfc2',
       '581ccd016c73180001fa5b2a', '5b97f2375612b30001acc4c9',
       '61698a8779cd6c1922b2a204', '654676d73282e9e8d26d129f',
       '64401708880c30ec28b9aef4', '60fd310fff5b2600c9d95554',
       '6078b85e024d1d094113c3aa', '629f6b8c65fcae219e245284',
       '637545d6428d85daeedc3df5', '6229dc51dff340226697778e',
       '5ae9cde00335e200019e9eed', '5696b105eaa915000b8bd77c',
       '62c6ad01d7ad711abdf2eb4c', '5fb551ccab996500099ab1aa',
       '60375d67dde85cad87f3c99d', '5c7b8c1237d77b00158b4e39',
       '60dc4e2299f89a7ca94b2c91', '5b5f23420085cb0001872849',
       '636166e1694fe8d9ed77dd68', '6400e0dd862feacb579475a8',
       '5c559af233ed050001dffa66', '64217d8202361ad4dbed3596',
       '5b222aff59f9620001c109cb', '5f392fae9168cc472f0468f6',
       '566feba6b937e400052d33b2', '6562025a6e3331528cf8fb3d',
       '5f8dec421f06451776393dc4', '5b5df59dd113f600012de8e9',
       '6501b789e3ddbc0a0b79b925', '6613a814a0c2d6cb21da8ef8',
       '647869e6f69318bacc341d53', '649cbefc9ac085131a41f626',
       '646bd812bf93129feeb5a3dc', '6413a4a1a6e064ffb173f1ce',
       '6609688e8e4fe9698ab13a66', '5dc5da21d999de45a504651b',
       '63fbf0e3b18cc14adc0dbfb6', '66082366bf2c333472dfc339',
       '65e8d383f3c7e1afd7b5c98f', '62682277645054f5802459b8',
       '5c5cad3e4ee81200018eafe2', '5f3e6a07e06e71069f919082',
       '63cd461c5f597e27b2a054fb', '63beebaa4c5884797ff00a98',
       '660724a45eceb43b0c11aeb9', '60b542b8fbb1a6a2678f5054',
       '650ee274aa4447ac435b7830', '5d76d2f7daf4bf00164d585b',
       '5f6f7258aa7332501adb94f4', '65c3a03ff621c50711765546',
       '6612d0a9046c003fef7f5e16', '59d9d9cd8fd07a0001842484',
       '5f088ba29bf08d0b3885f726', '61015f63f9a351d3171a0f98',
       '65b876fb5cc28b62953115fc', '5d68c8aa40524c00189e8ac2',
       '5588b2bffdf99b7a7714efd1', '5780d9a1900cc80001d2d1c2',
       '641384b3dffcf39ec42d3c23', '657b91830c807b69681bf0ef',
       '6508518b906002118153f087', '60d6f47f9ee6d5613df44943',
       '5fa407c0cf3d4f07e93fb5a0', '6107ca62e9040e3847a1bd17',
       '5bfece626e6cd80001beb6c0', '57b889c1e163b10001abf340',
       '65cf8daaaf679c7816f3a1b4', '644a4cace89b63c509a1e3df',
       '59e7eb5d62637600014a7db2', '5f4fa43ff313fc07706bb0fe',
       '5f2475017bdf7404b8215eef', '5d29a65b5b3b1f001aaaf6e3',
       '63ef938aea545fb9bd19a591', '5dbf5fe16849043f135aa2c0',
       '609a9aae2e53d2c195a1bba6', '5a7659fd8fe2dc00010573be',
       '65b245ff936ba04dd1bfbe42', '637fcee60a8378c1c3a65898',
       '637e1c1af194c6e63e8ff286', '654983b42d3870e2a88c6fe4',
       '61474f07f4cfbc50cb3b2f1e', '634842a70942fb4ba6aa1e88',
       '63d3fb730f03adf8b4a28a37', '63ee9abfa262bea95766dd9c',
       '660d6a1f4a7f1337de235daa', '59660b07e549e90001e44daa',
       '64860c8cfd693e6467ad6d15', '6539185ae1c6f8b919b85f12',
       '6447a21bdb359b012f49465b', '58acbfacea3d11000170e99a',
       '62f3b543dce069211e8e982c', '5f280cc370354e08a8f2895c',
       '6234a3d5cd2f63c705e5842d', '651ae29f9334283dc9199467',
       '5eaecb0824839e59ed3523eb', '602e913f090088a4ec214921',
       '5f0f7fe1d7ad1c000b42d091', '5c50efd2cc71f4000125ce0d',
       '6547cc9659e7f644c638ff4d', '65580768f9436cc14ed21839',
       '61282ca83be28773ac7c421f', '5c5ca0ce4ee81200018eaf51',
       '642b3aab1e4144843eb82d33', '5a5e14fc8e625900017626a9',
       '5c366fc38821900001b38b67', '63cf80c4d375aee306c35b26',
       '6156fef09d1ab07148870099', '5eb7dec5245b8670ff3536f2',
       '65fd99e73ff53a8211e10e71', '582f8bbd4cadc80001b0fbd3',
       '604e7009ec21c0e9b6990c6f', '643586e85e731b5eec977508',
       '5fcfb1fe79b8060e0662270a', '62b4370c9a89e5a09c4447de',
       '6557ebf8541bd32382739c1a', '58bef6fd31de840001e84ba0',
       '65e8c60269bf545c378b7853', '64581c19e5e95ab59f07be23',
       '657873a2a8c5516a28606b5e', '5f7af40fe087e400087a9f16',
       '5be8721025507300010dc142', '5e553f8783c96c539f0d101e',
       '60a420249c993b3fda36dfe6', '5c93073250e4fb0001f7907b',
       '60fa0929b83c13a26cd1b8d7', '6050acf587bc4d19589f8002',
       '60458ea6add21e6e79166fc8', '5de25e3fce20cd28846a7d5b',
       '5fb07c9ec19dcc47ed7175a7', '63f77cac11a2ddb8e7276c44',
       '6548f985729af1f81c1f92eb', '5d8878251f684d0001737c56',
       '5e7bc150e9efba1eeee1a9ca', '60173ba4df028898aa20838a',
       '5b25100be72c860001632802', '60ec17bbca621383f7703474',
       '5d7f598628843a00181eb444', '59b044b4d98aab00019bad5a',
       '576311d7151e5d000889e2e7', '609c2dcbc88bdd19e0be4b98',
       '57be9976c5234c00014706c1', '5a8d6772f49c9a0001f3cd72',
       '5eea7f7eeaccd018d7218549', '5f5a5d4618746310515e2828',
       '6023f94d1951e70ae21770ec', '65385b6fc5c3ece263dc6085',
       '65aac5df3acade1364859d7f', '5b22d5a51eef1b00016f3bbf',
       '6567ae0e8905da3905e013bf', '5c50046b2b89f500015e5f6b',
       '6566513f9e98445866f964f1', '59fc8aba087f2e0001ead671',
       '5d53bffa147a7d00015aae5a', '5e99c8efae829502a02f6fc8',
       '5f0749f67f6e1a31b1a0b918', '6346e10721ce6a0ebc5a5907',
       '6518cf249463264599a7918d', '5978f6f009bdcf000153f43d',
       '58174d95a22f0f0001a3f0be', '613dd1a6c18d06d2e464131b',
       '63e61d24e1c77b4b584e879f', '62714a240ed387f760f6741b',
       '6525684f0a285b2386b10497', '65be5c84defe30b60960f46f',
       '5cd89ac3575359001dc46b76', '5c4b987538878c0001c7883b',
       '65de18036cf5d10beb26c723', '63468b5809bf04222262bfed',
       '65bd29a33fe10dcc8e183b52', '6034da6b08183eee8cc990ea',
       '5f4a33e6d0e4f9031cdc7428', '605d4d0ddbd0e2b1eccda697',
       '5ba17c2d6d7a520001bfabae', '5ad44f87459c35000113830e',
       '61716052a11968c4644776b7', '5ffd3f5a81fc4f21eaa9ba9f',
       '59497c498fb2140001afda85', '60a9e0e4d2741b11c3ed7b8f',
       '5b4b859e11d39e00017bc223', '5d7824b816dea6000130d65f',
       '65142b520a558f5b7e621b61', '6565f3b379d54150868b89d8',
       '65a3ec77f674ac3e98f0c6ac', '5c0a502a2bfc8b0001813992',
       '5b9b8570805e5d0001c61ad3', '63ced2ac873e8ce2bfbd9f0f',
       '630381b587675d45be2c3c16', '655bce993fccd0170a5a56a3',
       '5e1b307333e83535d72af1e5', '64dd27e89ef24c0b30506762',
       '65c4ecd8921782e1af2ed682', '63d05dfdf2faf2f6c3910784',
       '63d3f953f8fb0fe970f0d0c6', '5f7ea88de0017818591618df',
       '60461bfeeac81b04cf62f7a6', '644cdee223c4b93bf46c7301',
       '59609bdb599b690001ef2c59', '62e25115fb932baf4a93173f',
       '65e709a37544bf878029f5b4', '6413603a62c72120012e05be',
       '5b2c0994f1ca3c000190196a', '606041fc7e7b32b934840f3d',
       '63e96aac1a64f6442aeadf72', '6546571a2570caaa0d2db83c',
       '62a33c442c64c9d129b53f32', '59e795c062637600014a7d3f',
       '6530316e660f5b8d9c11c00e', '6529425c8642a206285c998b',
       '6315fd72852e279a1a13e5f1', '5c41e9263be7b70001fcf4ab',
       '6432af145a86d0d903904850', '65798c4acc7fdd994909cb76',
       '6545c72ce36b05a1f97d2052', '5ec96e3609117f0a67231842',
       '63cee98c7cce75401646795a', '6400c176195e0363ae8f6e1f',
       '639b9b047b98a3d09a77a6c6', '6599643febd11bae8858cc8a',
       '657421f9661ce9a8cd7482d1', '5eadaff848b26f4483ae62d9',
       '5996d2256b939900012d9f22', '5d8cb1c93a7d5c00196eae92',
       '5e4886f1da7b943284265869', '5774ed97d8e8880001b2ff6c',
       '6607f7bf9cd99845dfeadef5', '5fe1053fad8fbab3583b4ecf',
       '577bfa3c9fecfe0001a5bcbf', '5e332dec41d1cd30b905bdfe',
       '62c1f284b5ce5f4d8840ea7c', '62a447d91e71bfacd2e8c006'],
      dtype=object)

In [14]:
len(processed_df.participant_id.unique())

316

In [15]:
counts = processed_df.groupby("participant_id").transform("size")

# Filter the DataFrame based on counts greater than 10
filtered_df = processed_df[counts > 10]

In [16]:
filtered_df

Empty DataFrame
Columns: [participant_id, start_time, end_time, video_id, joy, sadness, fear, anger, disgust, surprise, other, other_text, pleasure, arousal, dominance, appraisal]
Index: []

In [17]:
videos_covered = set(processed_df.video_id.unique())

In [18]:
len(videos_covered)

512

In [19]:
all_videos = set(range(1,513))

In [20]:
all_videos.difference(videos_covered)

set()

In [21]:
len(all_videos.difference(videos_covered))

0

In [29]:
counts = processed_df.groupby("video_id").transform("size")

# Filter the DataFrame based on counts greater than 1
filtered_df = processed_df[counts == 5]

In [30]:
sorted(filtered_df.video_id.unique())

[393, 464, 466]

In [31]:
len(filtered_df.video_id.unique())

3

In [32]:
count = {}

for i in range(1, 11):
    filtered_df = processed_df[counts == i]
    count[i] = len(filtered_df.video_id.unique())

In [38]:
count

{1: 0, 2: 0, 3: 0, 4: 0, 5: 3, 6: 420, 7: 88, 8: 0, 9: 1, 10: 0}

In [34]:
len(processed_df.video_id.unique()) + len(all_videos.difference(videos_covered))

512

In [35]:
processed_df[processed_df.video_id == 331]

,participant_id,start_time,end_time,video_id,joy,sadness,fear,anger,disgust,surprise,other,other_text,pleasure,arousal,dominance,appraisal
468,653fcb1b0f5d689c00a97629,5/3/24 16:57,5/3/24 18:04,331,Low,Low,High,Average,High,High,NaN,NaN,3,7,7,The robot is facing a challenge or obstacle th...
679,5ea6df209d688606829ac644,5/8/24 18:39,5/8/24 19:07,331,NaN,Very Low,High,NaN,NaN,Very Low,NaN,NaN,5,9,6,The robot looks like it's doing something susp...
1134,5b5df59dd113f600012de8e9,5/8/24 21:15,5/8/24 21:54,331,NaN,NaN,Very High,High,NaN,High,NaN,NaN,3,6,6,The robot may be confused or in search of some...
1927,6156fef09d1ab07148870099,5/9/24 13:10,5/9/24 13:38,331,NaN,Low,Very Low,Very Low,NaN,NaN,NaN,NaN,4,5,4,seemed like trying to find something
2444,58174d95a22f0f0001a3f0be,5/9/24 20:12,5/9/24 20:32,331,NaN,Low,High,NaN,NaN,Very Low,NaN,NaN,1,7,3,The robot seemed frightened to move around too...
2524,65de18036cf5d10beb26c723,5/9/24 20:13,5/9/24 21:20,331,NaN,Very High,NaN,Average,NaN,NaN,NaN,NaN,2,4,3,"the robot looks sad and angry, that is why it ..."
2546,65bd29a33fe10dcc8e183b52,5/9/24 13:39,5/9/24 22:11,331,Low,Very Low,Very Low,Average,Average,Very Low,NaN,NaN,2,9,7,"The robot is alert, and moderately angry and d..."
2886,63e96aac1a64f6442aeadf72,5/10/24 11:52,5/10/24 12:12,331,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,1,4,1,Robot seems to be alarmed by something
2987,6545c72ce36b05a1f97d2052,5/10/24 12:38,5/10/24 13:06,331,NaN,Low,Very Low,Very Low,NaN,NaN,NaN,NaN,2,1,2,Robot is going around in circles and staying t...